### ISSUE TITLE
supply k=None for first_lexical?

### ISSUE THREAD

**Issue by smichr** [klocey/partitions#23]
If the args were changed to `first_lexical(q, n, k=None)` it would make that routine a little easier to use since it would then automatically give the correct starting value without having to think about what k will be.

``` python
def first_lexical(q, n, k) -> def first_lexical(q, n, k=None)
```

**Comment by klocey** [comment]
@smichr Thanks very much for the issues you raised. I haven't used this repo or its code in years and, so, didn't see your comments. Now that I'm taking up another integer partitioning project, I'll be sure to consider your comments.

**Comment by klocey** [comment]
Done. Thanks @smichr.
